package com.dsky.baas.pointsservice.model;

import java.io.Serializable;

public class ExchangeOrder implements Serializable {
 
	private static final long serialVersionUID = -1466729920359959243L;

	public static final String STATUS_REQUESTED = "REQUESTED";
	public static final String STATUS_PASSED = "PASSED";
	public static final String STATUS_REJECTED = "REJECTED";
	public static final String STATUS_PAID = "PAID";

	
	//表自增id
    private Integer id;


    //订单编号
    private String orderId;

    //用户id
    private Long playerId;


   //游戏id

    private Integer gameId;


  //配置兑换计划

    private Integer planId;

    //游戏等级

    private Integer level;


  //在线时长
    private Integer onlineTime;


   //已有积分
    private Integer hasPoints;


   //可兑换积分
    private Integer requestExchangePoints;


  //支付账号
    private Integer amount;

    //支付方式
    private Integer payMethod;

  //支付相关信息
    private String payInfo;


    //用户备注
    private String userMemo;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exchange_order.operation_memo
     *
     * @mbggenerated
     */
    private String operationMemo;

    //审核状态
    private String status;

    //创建时间
    private Integer createAt;
    
    //删除时间
    private Integer deleteAt;
    
    //分页起始行
    private Integer startRow ;
    //分页结束行
    private Integer   endRow;
    

  
    public Integer getStartRow() {
		return startRow;
	}


	public void setStartRow(Integer startRow) {
		this.startRow = startRow;
	}


	public Integer getEndRow() {
		return endRow;
	}


	public void setEndRow(Integer endRow) {
		this.endRow = endRow;
	}


	public Integer getId() {
        return id;
    }

   
    public void setId(Integer id) {
        this.id = id;
    }

    
    public String getOrderId() {
        return orderId;
    }

   
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    
    public Long getPlayerId() {
        return playerId;
    }

    
    public void setPlayerId(Long playerId) {
        this.playerId = playerId;
    }

    
    public Integer getGameId() {
        return gameId;
    }

   
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

   
    public Integer getPlanId() {
        return planId;
    }

    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

  
    public Integer getLevel() {
        return level;
    }

    
    public void setLevel(Integer level) {
        this.level = level;
    }

  
    public Integer getOnlineTime() {
        return onlineTime;
    }

   
    public void setOnlineTime(Integer onlineTime) {
        this.onlineTime = onlineTime;
    }

    
    public Integer getHasPoints() {
        return hasPoints;
    }

   
    public void setHasPoints(Integer hasPoints) {
        this.hasPoints = hasPoints;
    }

   
    public Integer getRequestExchangePoints() {
        return requestExchangePoints;
    }

    
    public void setRequestExchangePoints(Integer requestExchangePoints) {
        this.requestExchangePoints = requestExchangePoints;
    }

   
    public Integer getAmount() {
        return amount;
    }

    
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    
    public Integer getPayMethod() {
        return payMethod;
    }

    
    public void setPayMethod(Integer payMethod) {
        this.payMethod = payMethod;
    }

   
    public String getPayInfo() {
        return payInfo;
    }

    
    public void setPayInfo(String payInfo) {
        this.payInfo = payInfo == null ? null : payInfo.trim();
    }

   
    public String getUserMemo() {
        return userMemo;
    }

   
    public void setUserMemo(String userMemo) {
        this.userMemo = userMemo == null ? null : userMemo.trim();
    }

    public String getOperationMemo() {
        return operationMemo;
    }

    public void setOperationMemo(String operationMemo) {
        this.operationMemo = operationMemo == null ? null : operationMemo.trim();
    }
    
    
    public String getStatus() {
        return status;
    }

    
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    public Integer getCreateAt() {
        return createAt;
    }

   
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    
    public Integer getDeleteAt() {
        return deleteAt;
    }

    
    public void setDeleteAt(Integer deleteAt) {
        this.deleteAt = deleteAt;
    }
}